name: Build Release Binaries

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Display the version of go that we have installed
        run: go version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Release notes
        env:
          RELEASE_NOTES: |
            This is a long string
            that spans multiple lines
            and all newlines will be preserved
        run: |
          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"Release notes for $RELEASE_NOTES\"}" \
            "https://api.github.com/repos/otoolep/gh-actions-test/releases/${{ github.event.release.id }}"
